sudo: false
language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm
services: sqlite3
before_script:
    - composer self-update
script:
    - composer install --prefer-source
    - chmod -R 777 tests/build
    - ./vendor/bin/phpunit
after_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then php vendor/bin/coveralls -v; fi
